Attempt to push a Github release

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -29,13 +29,29 @@ jobs:
   publish:
     <<: *setup
     docker:
-      - image: circleci/node:14
+      # TODO: Find a maintained image that provides `ghr`? This one is 2 years
+      # un-updated, but recommended by CircleCI here:
+      # https://circleci.com/blog/publishing-to-github-releases-via-circleci/
+      - image: cibuilds/github:0.13.0
     steps:
       - attach_workspace:
           at: ~/ros-animator-widget
-      - run: 
-          name: Publish
-          command: ls -la ~/ros-animator-widget/dist
+      - run:
+          name: Publish to GitHub Release
+          command: |
+            if [ ! -z "${GITHUB_TOKEN}" ]; then
+              echo "\$GITHUB_TOKEN not found. Aborting."
+              exit 1
+            fi
+            version=${CIRCLE_TAG}
+
+            ghr \
+              -prerelease \
+              -t "${GITHUB_TOKEN}" \
+              -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}"
+              "${version}" ~/ros-animator-widget/dist/bundle.min.js
+
+      # TODO: npm publish with build dir (and dist?)?
 
 
 workflows:
@@ -53,6 +69,6 @@ workflows:
             - test-and-build
           filters:
             branches:
-              only: main
+              ignore: /.*/
             tags:
               only: /^v[0-9]+(\.[0-9]+)*(\.[\-a-zA-Z0-9]+)?$/
